server:
  port: 9005

spring:
  application:
    name: HYSTRIX-DASHBOARD
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serive-url:
      defaultzone: http://localhost:8761/eureka/
  instance:
    hostname: localhost